### ISSUE TITLE
Suspect reset_index is dangerous, may need code fixes

### ISSUE THREAD

**Issue by csibbitt** [redhat-service-assurance/service-assurance-operator#32]
This looks wrong: https://github.com/redhat-service-assurance/service-assurance-operator/blob/master/roles/serviceassurance/tasks/component_events_smartgateway.yml#L21

According to the SG help[1], this will "Clean all index before on start". This is unconfirmed, but I think during testing I noted this would actually remove all existing events. I inquired about turning this off, and apparently it causes problems because the index won't exist to be written into. If both of these things are true, then this is a major problem we need to solve ASAP.

[1] https://github.com/redhat-service-assurance/smart-gateway/blob/ecb6c2d00b500c687a10407494d51270e185e89e/internal/pkg/events/events.go#L200

**Comment by csibbitt** [comment]
@elfiesmelfie Since you've been working with ES, can you take a peek at this?

**Comment by leifmadsen** [comment]
So I can confirm that just changing the `reset_index` to `false` will result in what we want. Chris had noted that a full test where a new instance of the Elasticsearch volume was refreshed is what we should really check. Here is information around spot testing where an index is not found on index list, and then shows up when `reset_index: false`.

```
ES_PASS=$(oc get secret elasticsearch-es-elastic-user -o go-template='{{ .data.elastic | base64decode }}')

curl --insecure --user elastic:$ES_PASS https://elasticsearch-sa-telemetry.apps.saftest.lab.rdu2.cee.redhat.com/_cat/indices

# no indices are returned
# run `ifdown vlan20 ; ifup vlan20` on compute-0

curl --insecure --user elastic:$ES_PASS https://elasticsearch-sa-telemetry.apps.saftest.lab.rdu2.cee.redhat.com/_cat/indices
yellow open collectd_connectivity yZ6aSKj8R4mt3ITBCpA7Zw 1 1 2 0 29.6kb 29.6kb
```

Setup and test was the following:

* stand up SG with `reset_index: true`
* network up/down
* event and index seen in ES
* SG pod deleted
* index no longer returned in ES

* set `reset_index: false` in SG config
* delete SG pod to load new configuration
* network up/down
* event and index seen in ES
* SG pod deleted
* event and index still returns
* network up/down
* document count in existing index in ES is increased by expected number
